sudo: required
services:
  - docker
before_install:
  - docker build -t cloudnloud/iamshyfail:v1.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push cloudnloud/iamshyfail:v1.0
notifications:
  email:
    recipients:
      - hedewes545@alfaceti.com
    on_success: always
    on_failure: always
